stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: vue-natuer-remo:develop
      registry: 127.0.0.1:34036
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification:
  recipients:
  - recipient: '#k3s-nuc'
    notifier: local:n-8k7lm
  condition:
  - Success
  - Changed
  - Failed
