stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: haku-mai/vue-natuer-remo:develop
      pushRemote: true
      registry: core.harbor.k3s.nuc
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification:
  recipients:
  - recipient: '#k3s-nuc'
    notifier: local:n-8k7lm
  condition:
  - Success
  - Changed
  - Failed
