stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: haku-mai/vue-natuer-remo:test
      pushRemote: true
      registry: 10.43.122.123:5000
    env:
      PLUGIN_INSECURE: "true"
- name: run pod
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#k3s-nuc'
    notifier: local:n-8k7lm
  condition:
  - Success
  - Changed
  - Failed
