stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: vue
      pushRemote: true
      registry: http://192.168.68.108:30615
timeout: 60
notification: {}
