stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: vue-natuer-remo:develop
      registry: http://192.168.68.108:30615
- name: run pod
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
