stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: haku-mai/vue-natuer-remo:develop
      pushRemote: true
      registry: docker-registry.default.svc.cluster.local:5000
    env:
      PLUGIN_INSECURE: "true"
- name: run deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#k3s-nuc'
    notifier: local:n-8k7lm
  condition:
  - Success
  - Changed
  - Failed
